# Generated by Django 4.1.6 on 2023-03-14 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_check', models.BigIntegerField(verbose_name='Всего просмотрено')),
                ('new_accept', models.BigIntegerField(verbose_name='Поинтов одобрено')),
                ('new_deny', models.BigIntegerField(verbose_name='Поинтов отклонено')),
                ('new_dubls', models.BigIntegerField(verbose_name='Найдено дублей')),
                ('update_accept', models.BigIntegerField(verbose_name='Обновлений одобрено')),
                ('update_deny', models.BigIntegerField(verbose_name='Обновлений отклонено')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика игрока',
                'verbose_name_plural': 'Статистика игроков',
            },
        ),
        migrations.CreateModel(
            name='UsersLvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.BigIntegerField(verbose_name='Уровень')),
                ('exp', models.BigIntegerField(verbose_name='Опыт')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уровень игрока',
                'verbose_name_plural': 'Уровни игроков',
            },
        ),
    ]
