# Generated by Django 4.1.6 on 2023-04-07 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted', models.TextField(verbose_name='Уникальный ключ')),
                ('password', models.TextField(verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Линк пароль',
                'verbose_name_plural': 'Линк пароли',
            },
        ),
        migrations.CreateModel(
            name='LinkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgdata', models.TextField(verbose_name='Инфа с тг')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Линк дата',
                'verbose_name_plural': 'Линк дата',
            },
        ),
    ]
