# Generated by Django 4.1.6 on 2023-03-14 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslvl',
            name='user_nick',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersstats',
            name='user_nick',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
