# Generated by Django 4.1.6 on 2023-04-07 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_linkpassword_linkdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpassword',
            name='tgdata',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Инфа с тг'),
            preserve_default=False,
        ),
    ]
