# Generated by Django 4.1.6 on 2023-04-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_linkpassword_tgdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpassword',
            name='password',
            field=models.TextField(null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='linkpassword',
            name='tgdata',
            field=models.TextField(null=True, verbose_name='Инфа с тг'),
        ),
    ]
