# Generated by Django 4.1.6 on 2023-04-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_linkpassword_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslvl',
            name='exp',
            field=models.BigIntegerField(null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='userslvl',
            name='lvl',
            field=models.BigIntegerField(null=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='userslvl',
            name='user_nick',
            field=models.TextField(null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='usersstats',
            name='new_accept',
            field=models.BigIntegerField(null=True, verbose_name='Поинтов одобрено'),
        ),
        migrations.AlterField(
            model_name='usersstats',
            name='new_deny',
            field=models.BigIntegerField(null=True, verbose_name='Поинтов отклонено'),
        ),
        migrations.AlterField(
            model_name='usersstats',
            name='new_dubls',
            field=models.BigIntegerField(null=True, verbose_name='Найдено дублей'),
        ),
        migrations.AlterField(
            model_name='usersstats',
            name='total_check',
            field=models.BigIntegerField(null=True, verbose_name='Всего просмотрено'),
        ),
        migrations.AlterField(
            model_name='usersstats',
            name='update_accept',
            field=models.BigIntegerField(null=True, verbose_name='Обновлений одобрено'),
        ),
        migrations.AlterField(
            model_name='usersstats',
            name='update_deny',
            field=models.BigIntegerField(null=True, verbose_name='Обновлений отклонено'),
        ),
        migrations.AlterField(
            model_name='usersstats',
            name='user_nick',
            field=models.TextField(null=True, verbose_name='Имя пользователя'),
        ),
    ]
